import type { Asset, Collection } from '@/types'

// ─────────────────────────────────────────────────────────────
// MOCK DATA — used when DROPBOX_ACCESS_TOKEN is not set
// Replace with real Dropbox data in production
// ─────────────────────────────────────────────────────────────

export const MOCK_ASSETS: Asset[] = [
  {
    id: 'mock-1',
    name: 'Primary-Logo-Dark.png',
    displayName: 'Primary Logo Dark',
    path: '/Brand Logos/Primary-Logo-Dark.png',
    type: 'image',
    extension: 'png',
    size: 245760,
    sizeFormatted: '240 KB',
    modified: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    dropboxId: 'mock-1',
    thumbnailUrl: 'https://placehold.co/400x300/1a0f09/8B5E3C?text=Logo+Dark&font=playfair-display',
    tags: ['logo', 'brand logos', 'dark', 'primary'],
    collection: 'Brand Logos',
    collectionPath: '/Brand Logos',
    isNew: true,
    access: 'public',
    mimeType: 'image/png',
    width: 2400,
    height: 1200,
  },
  {
    id: 'mock-2',
    name: 'Primary-Logo-Light.png',
    displayName: 'Primary Logo Light',
    path: '/Brand Logos/Primary-Logo-Light.png',
    type: 'image',
    extension: 'png',
    size: 198000,
    sizeFormatted: '193 KB',
    modified: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    dropboxId: 'mock-2',
    thumbnailUrl: 'https://placehold.co/400x300/f5f0eb/8B5E3C?text=Logo+Light&font=playfair-display',
    tags: ['logo', 'brand logos', 'light', 'primary'],
    collection: 'Brand Logos',
    collectionPath: '/Brand Logos',
    isNew: true,
    access: 'public',
    mimeType: 'image/png',
    width: 2400,
    height: 1200,
  },
  {
    id: 'mock-3',
    name: 'Icon-Mark.svg',
    displayName: 'Icon Mark',
    path: '/Brand Logos/Icon-Mark.svg',
    type: 'svg',
    extension: 'svg',
    size: 8400,
    sizeFormatted: '8.2 KB',
    modified: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    dropboxId: 'mock-3',
    thumbnailUrl: 'https://placehold.co/400x300/2d1d11/c09d7d?text=✦+Icon&font=playfair-display',
    tags: ['logo', 'brand logos', 'icon', 'mark', 'svg'],
    collection: 'Brand Logos',
    collectionPath: '/Brand Logos',
    isNew: true,
    access: 'public',
    mimeType: 'image/svg+xml',
  },
  {
    id: 'mock-4',
    name: 'Brand-Guidelines.pdf',
    displayName: 'Brand Guidelines',
    path: '/Brand Guidelines/Brand-Guidelines.pdf',
    type: 'pdf',
    extension: 'pdf',
    size: 8500000,
    sizeFormatted: '8.1 MB',
    modified: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    dropboxId: 'mock-4',
    thumbnailUrl: 'https://placehold.co/400x300/432b1a/e8ddd0?text=Brand+Guidelines&font=playfair-display',
    tags: ['guidelines', 'brand guidelines', 'pdf', 'brand'],
    collection: 'Brand Guidelines',
    collectionPath: '/Brand Guidelines',
    isNew: false,
    access: 'public',
    mimeType: 'application/pdf',
  },
  {
    id: 'mock-5',
    name: 'Social-Template-Instagram.png',
    displayName: 'Social Template Instagram',
    path: '/Social Media/Social-Template-Instagram.png',
    type: 'image',
    extension: 'png',
    size: 1200000,
    sizeFormatted: '1.1 MB',
    modified: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    dropboxId: 'mock-5',
    thumbnailUrl: 'https://placehold.co/400x400/5a3a23/d4bfa8?text=Instagram+Template&font=playfair-display',
    tags: ['social', 'social media', 'instagram', 'template'],
    collection: 'Social Media',
    collectionPath: '/Social Media',
    isNew: true,
    access: 'public',
    mimeType: 'image/png',
    width: 1080,
    height: 1080,
  },
  {
    id: 'mock-6',
    name: 'Brand-Video-30s.mp4',
    displayName: 'Brand Video 30s',
    path: '/Video Assets/Brand-Video-30s.mp4',
    type: 'video',
    extension: 'mp4',
    size: 45000000,
    sizeFormatted: '42.9 MB',
    modified: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    dropboxId: 'mock-6',
    thumbnailUrl: 'https://placehold.co/400x225/1a0f09/a87c58?text=▶+Brand+Video&font=playfair-display',
    tags: ['video', 'video assets', 'brand'],
    collection: 'Video Assets',
    collectionPath: '/Video Assets',
    isNew: false,
    access: 'public',
    mimeType: 'video/mp4',
    width: 1920,
    height: 1080,
  },
  {
    id: 'mock-7',
    name: 'Color-Palette.pdf',
    displayName: 'Color Palette',
    path: '/Brand Guidelines/Color-Palette.pdf',
    type: 'pdf',
    extension: 'pdf',
    size: 2100000,
    sizeFormatted: '2.0 MB',
    modified: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    dropboxId: 'mock-7',
    thumbnailUrl: 'https://placehold.co/400x300/704a2e/f5f0eb?text=Color+Palette&font=playfair-display',
    tags: ['color', 'brand guidelines', 'palette'],
    collection: 'Brand Guidelines',
    collectionPath: '/Brand Guidelines',
    isNew: false,
    access: 'public',
    mimeType: 'application/pdf',
  },
  {
    id: 'mock-8',
    name: 'Product-Shot-Hero.jpg',
    displayName: 'Product Shot Hero',
    path: '/Photography/Product-Shot-Hero.jpg',
    type: 'image',
    extension: 'jpg',
    size: 3400000,
    sizeFormatted: '3.2 MB',
    modified: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    dropboxId: 'mock-8',
    thumbnailUrl: 'https://placehold.co/400x500/2d1d11/c09d7d?text=Product+Hero&font=playfair-display',
    tags: ['photography', 'product', 'hero'],
    collection: 'Photography',
    collectionPath: '/Photography',
    isNew: true,
    access: 'public',
    mimeType: 'image/jpeg',
    width: 4000,
    height: 5000,
  },
  {
    id: 'mock-9',
    name: 'Logos-Package.zip',
    displayName: 'Logos Package',
    path: '/Brand Logos/Logos-Package.zip',
    type: 'archive',
    extension: 'zip',
    size: 12000000,
    sizeFormatted: '11.4 MB',
    modified: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    dropboxId: 'mock-9',
    thumbnailUrl: 'https://placehold.co/400x300/432b1a/e8ddd0?text=📦+Logo+Package&font=playfair-display',
    tags: ['logo', 'brand logos', 'zip', 'archive', 'package'],
    collection: 'Brand Logos',
    collectionPath: '/Brand Logos',
    isNew: false,
    access: 'public',
    mimeType: 'application/zip',
  },
  {
    id: 'mock-10',
    name: 'OG-Image.png',
    displayName: 'OG Image',
    path: '/Social Media/OG-Image.png',
    type: 'image',
    extension: 'png',
    size: 450000,
    sizeFormatted: '439 KB',
    modified: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    dropboxId: 'mock-10',
    thumbnailUrl: 'https://placehold.co/400x210/8B5E3C/f5f0eb?text=OG+Image&font=playfair-display',
    tags: ['social', 'social media', 'og', 'web'],
    collection: 'Social Media',
    collectionPath: '/Social Media',
    isNew: true,
    access: 'public',
    mimeType: 'image/png',
    width: 1200,
    height: 630,
  },
  {
    id: 'mock-11',
    name: 'Typography-Guide.pdf',
    displayName: 'Typography Guide',
    path: '/Brand Guidelines/Typography-Guide.pdf',
    type: 'pdf',
    extension: 'pdf',
    size: 5600000,
    sizeFormatted: '5.3 MB',
    modified: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    dropboxId: 'mock-11',
    thumbnailUrl: 'https://placehold.co/400x300/1a0f09/d4bfa8?text=Typography+Guide&font=playfair-display',
    tags: ['typography', 'brand guidelines', 'pdf'],
    collection: 'Brand Guidelines',
    collectionPath: '/Brand Guidelines',
    isNew: false,
    access: 'public',
    mimeType: 'application/pdf',
  },
  {
    id: 'mock-12',
    name: 'Packaging-Mockup-Front.png',
    displayName: 'Packaging Mockup Front',
    path: '/Photography/Packaging-Mockup-Front.png',
    type: 'image',
    extension: 'png',
    size: 4100000,
    sizeFormatted: '3.9 MB',
    modified: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    dropboxId: 'mock-12',
    thumbnailUrl: 'https://placehold.co/400x480/2d1d11/a87c58?text=Packaging+Mockup&font=playfair-display',
    tags: ['photography', 'packaging', 'mockup'],
    collection: 'Photography',
    collectionPath: '/Photography',
    isNew: true,
    access: 'partner',
    mimeType: 'image/png',
    width: 3000,
    height: 3600,
  },
]

export const MOCK_COLLECTIONS: Collection[] = [
  {
    id: 'col-1',
    name: 'Brand Logos',
    path: '/Brand Logos',
    assetCount: 3,
    coverAsset: MOCK_ASSETS[0],
    description: 'Official logo files in all formats and color variants',
    access: 'public',
    lastModified: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'col-2',
    name: 'Brand Guidelines',
    path: '/Brand Guidelines',
    assetCount: 3,
    coverAsset: MOCK_ASSETS[3],
    description: 'Complete brand guidelines, color palettes, and typography specs',
    access: 'public',
    lastModified: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'col-3',
    name: 'Social Media',
    path: '/Social Media',
    assetCount: 2,
    coverAsset: MOCK_ASSETS[4],
    description: 'Templates and assets for all social platforms',
    access: 'public',
    lastModified: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'col-4',
    name: 'Photography',
    path: '/Photography',
    assetCount: 2,
    coverAsset: MOCK_ASSETS[7],
    description: 'Official product photography and lifestyle imagery',
    access: 'public',
    lastModified: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'col-5',
    name: 'Video Assets',
    path: '/Video Assets',
    assetCount: 1,
    coverAsset: MOCK_ASSETS[5],
    description: 'Brand video content and motion graphics',
    access: 'public',
    lastModified: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
